   data {
"last_item": null,
"total_items": "9209",
"first_item": null,
"page_number": "1",
"page_size": "10",
"page_items": null,
"search_time": "0.06",
"page_count": "921",
"events": {
"event": [
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": "30076",
"going_count": null,
"all_day": "0",
"latitude": "34.0377719",
"groups": null,
"url": "http://atlanta.eventful.com/events/20-celebrate-20-roswell-performance-/E0-001-105251480-1?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-105251480-1",
"privacy": "1",
"city_name": "Roswell",
"link_count": null,
"longitude": "-84.3321130",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-09-30 16:00:00",
"tz_id": null,
"description": " The results are in: 20 musicians gather to celebrate 20 years of great music by the ABO, with selections chosen by you, our audience! Program selections include Handel&#39;s Water Music and Bach&#39;s Brandenburg Concerto No. 3, among other audience and musician favorites. Don&#39;t miss this special celebration featuring an impressive array of wind instruments - baroque piccolo/flute, oboes, natural horns, trumpets and bassoon! General Admission - Advance Purchase - $25.00 General Admission - Day of Concert - $30.00 Senior - Advance Purchase - $20.00 Senior - Day of Concert - $25.00 Student - Advance Purchase - $10.00 Student - Day of Concert - $15.00 AEMA Member - $10.00 Patron Tickets - $150.00",
"modified": "2017-08-01 04:00:54",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "20 Celebrate 20 - Roswell Performance",
"venue_address": "1015 Old Roswell Road",
"geocode_type": "EVDB Geocoder",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": {
"small": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/015/989/309-7.jpeg_/20-celebrate-20-roswell-performance-09.jpeg",
"height": "48"
},
"width": "48",
"caption": null,
"medium": {
"width": "128",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/015/989/309-7.jpeg_/20-celebrate-20-roswell-performance-09.jpeg",
"height": "128"
},
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/015/989/309-7.jpeg_/20-celebrate-20-roswell-performance-09.jpeg",
"thumb": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/015/989/309-7.jpeg_/20-celebrate-20-roswell-performance-09.jpeg",
"height": "48"
},
"height": "48"
},
"created": "2017-08-01 04:00:54",
"venue_id": "V0-001-004061579-1",
"tz_city": null,
"stop_time": null,
"venue_name": "St. David's Episcopal Church",
"venue_url": "http://atlanta.eventful.com/venues/st-davids-episcopal-church-/V0-001-004061579-1?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": "30076",
"going_count": null,
"all_day": "0",
"latitude": "34.0377719",
"groups": null,
"url": "http://atlanta.eventful.com/events/arcadia-roswell-performance-/E0-001-105251574-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-105251574-9",
"privacy": "1",
"city_name": "Roswell",
"link_count": null,
"longitude": "-84.3321130",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2018-04-21 16:00:00",
"tz_id": null,
"description": " ABO&#39;s Artistic Administrator and Violinist Evan Few takes the helm as Guest Director for our final concert of the season, celebrating the flourishing of musical arts in 17th- and 18-century Rome with a program featuring selections from Arcangelo Corelli&#39;s beloved Concerti Grossi and a variety of other gems from members of his circle. General Admission - Advance Purchase - $25.00 General Admission - Day of Concert - $30.00 Senior - Advance Purchase - $20.00 Senior - Day of Concert - $25.00 Student - Advance Purchase - $10.00 Student - Day of Concert - $15.00 AEMA Member - $10.00 Patron Tickets - $150.00",
"modified": "2017-08-01 04:03:04",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "Arcadia - Roswell Performance",
"venue_address": "1015 Old Roswell Road",
"geocode_type": "EVDB Geocoder",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": {
"small": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/015/989/309-7.jpeg_/arcadia-roswell-performance-09.jpeg",
"height": "48"
},
"width": "48",
"caption": null,
"medium": {
"width": "128",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/015/989/309-7.jpeg_/arcadia-roswell-performance-09.jpeg",
"height": "128"
},
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/015/989/309-7.jpeg_/arcadia-roswell-performance-09.jpeg",
"thumb": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/015/989/309-7.jpeg_/arcadia-roswell-performance-09.jpeg",
"height": "48"
},
"height": "48"
},
"created": "2017-08-01 04:03:04",
"venue_id": "V0-001-004061579-1",
"tz_city": null,
"stop_time": null,
"venue_name": "St. David's Episcopal Church",
"venue_url": "http://atlanta.eventful.com/venues/st-davids-episcopal-church-/V0-001-004061579-1?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": "30012",
"going_count": null,
"all_day": "0",
"latitude": "33.7203",
"groups": null,
"url": "http://atlanta.eventful.com/events/design-thinking-workshop-educators-/E0-001-102226128-5?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-102226128-5",
"privacy": "1",
"city_name": "Conyers",
"link_count": null,
"longitude": "-84.0093",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-09-30 09:00:00",
"tz_id": null,
"description": " The Design Thinking for Educators Workshop will  give teachers  a better understanding of the methods they need to apply design thinking—discovery, interpretation, ideation, experimentation and evolution—in real-world scenarios. Cost: $25 per person (lunch included)   You will select one of the workshops listed below.  Pre K- 5th grade- Workshop  6th - 8th grade- Workshop  9th- 12th grade- Workshop  After lunch you will receive information on how to set up a donors choose campaign for resources you will need for your classroom or program.                                                            Registration is Limited ",
"modified": "2017-04-18 15:11:00",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "Design Thinking Workshop for Educators",
"venue_address": "406 Pleasant Hill Road Northwest",
"geocode_type": "Zip Code Based GeoCodes",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": {
"small": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/038/328/557-0.jpeg_/design-thinking-workshop-educators-57.jpeg",
"height": "48"
},
"width": "48",
"caption": null,
"medium": {
"width": "128",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/038/328/557-0.jpeg_/design-thinking-workshop-educators-57.jpeg",
"height": "128"
},
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/038/328/557-0.jpeg_/design-thinking-workshop-educators-57.jpeg",
"thumb": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/038/328/557-0.jpeg_/design-thinking-workshop-educators-57.jpeg",
"height": "48"
},
"height": "48"
},
"created": "2017-04-18 15:11:00",
"venue_id": "V0-001-008677698-4",
"tz_city": null,
"stop_time": null,
"venue_name": "406 Pleasant Hill Rd NW",
"venue_url": "http://atlanta.eventful.com/venues/406-pleasant-hill-rd-nw-/V0-001-008677698-4?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": null,
"going_count": null,
"all_day": "0",
"latitude": "33.7489",
"groups": null,
"url": "http://atlanta.eventful.com/events/1215-attend-develop-importexport-business-/E0-001-100277641-5?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-100277641-5",
"privacy": "1",
"city_name": "Atlanta",
"link_count": null,
"longitude": "-84.3881",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-12-15 09:30:00",
"tz_id": null,
"description": " Small businesses looking to increase sales and profit, reduce dependence on the domestic market and stabilize seasonal fluctuations should consider importing and exporting.  With nearly 96 percent of consumers living outside the U.S. and two-thirds of the world’s purchasing power in foreign countries, opportunities await U.S. small business.Go where the customers are. There is significant opportunity for small businesses to profit through importing and exporting operations.Do you have what it takes to become a successful international business? Are you ready to make international sales? Importing / Exporting offers great opportunities but requires preparation and planning.This is a two part series taught by international experts from the Georgia Small Business Development Center, a resource partner of the SBA.Module I will aid you in assessing your readiness, understanding what you need to know and consider before pursuing an international strategy. Module II will introduce you to those topics needed to develop and implement your strategy: international pricing and costing issues, proforma export quotations, payment terms, and risk assessment.The workshops will help you gain the knowledge to develop and implement an international  plan. You will become acquainted with the key components of an effective import / export plan.  The instructors will raise questions you should answer to complete your plan and provide the resources to help you answer those questions.    * organizational and product readiness,    * market research,    * guidance for developing your strategy and marketing plan,    * promoting your products in target market, and    * complying with US and foreign regulations. Fee for Module  I is $50 per person and is taught 9:30am - 12:30pmFee for Module II is $50 per person and is taught 1:15pm -  4:30pmBoth modules can be attended as a full day event for a single Fee of $89 per person ",
"modified": "2017-02-10 12:53:54",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "12/15 Attend Develop an Import/Export Business",
"venue_address": "233 Peachtree Street NE , 2nd Floor",
"geocode_type": "City Based GeoCodes",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": {
"small": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/037/789/148-6.jpeg_/1215-attend-develop-importexport-business-48.jpeg",
"height": "48"
},
"width": "48",
"caption": null,
"medium": {
"width": "128",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/037/789/148-6.jpeg_/1215-attend-develop-importexport-business-48.jpeg",
"height": "128"
},
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/037/789/148-6.jpeg_/1215-attend-develop-importexport-business-48.jpeg",
"thumb": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/037/789/148-6.jpeg_/1215-attend-develop-importexport-business-48.jpeg",
"height": "48"
},
"height": "48"
},
"created": "2017-02-10 12:53:54",
"venue_id": "V0-001-010992661-9",
"tz_city": null,
"stop_time": null,
"venue_name": "SBA Georgia District Office",
"venue_url": "http://atlanta.eventful.com/venues/sba-georgia-district-office-/V0-001-010992661-9?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": null,
"going_count": null,
"all_day": "0",
"latitude": "33.7489",
"groups": null,
"url": "http://atlanta.eventful.com/events/1117-attend-develop-importexport-business-/E0-001-100277602-6?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-100277602-6",
"privacy": "1",
"city_name": "Atlanta",
"link_count": null,
"longitude": "-84.3881",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-11-17 09:30:00",
"tz_id": null,
"description": " Small businesses looking to increase sales and profit, reduce dependence on the domestic market and stabilize seasonal fluctuations should consider importing and exporting.  With nearly 96 percent of consumers living outside the U.S. and two-thirds of the world’s purchasing power in foreign countries, opportunities await U.S. small business.Go where the customers are. There is significant opportunity for small businesses to profit through importing and exporting operations.Do you have what it takes to become a successful international business? Are you ready to make international sales? Importing / Exporting offers great opportunities but requires preparation and planning.This is a two part series taught by international experts from the Georgia Small Business Development Center, a resource partner of the SBA.Module I will aid you in assessing your readiness, understanding what you need to know and consider before pursuing an international strategy. Module II will introduce you to those topics needed to develop and implement your strategy: international pricing and costing issues, proforma export quotations, payment terms, and risk assessment.The workshops will help you gain the knowledge to develop and implement an international  plan. You will become acquainted with the key components of an effective import / export plan.  The instructors will raise questions you should answer to complete your plan and provide the resources to help you answer those questions.    * organizational and product readiness,    * market research,    * guidance for developing your strategy and marketing plan,    * promoting your products in target market, and    * complying with US and foreign regulations. Fee for Module  I is $50 per person and is taught 9:30am - 12:30pmFee for Module II is $50 per person and is taught 1:15pm -  4:30pmBoth modules can be attended as a full day event for a single Fee of $89 per person ",
"modified": "2017-02-10 12:53:03",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "11/17 Attend Develop an Import/Export Business",
"venue_address": "233 Peachtree Street NE , 2nd Floor",
"geocode_type": "City Based GeoCodes",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": {
"small": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/037/789/136-1.jpeg_/1117-attend-develop-importexport-business-36.jpeg",
"height": "48"
},
"width": "48",
"caption": null,
"medium": {
"width": "128",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/037/789/136-1.jpeg_/1117-attend-develop-importexport-business-36.jpeg",
"height": "128"
},
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/037/789/136-1.jpeg_/1117-attend-develop-importexport-business-36.jpeg",
"thumb": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/037/789/136-1.jpeg_/1117-attend-develop-importexport-business-36.jpeg",
"height": "48"
},
"height": "48"
},
"created": "2017-02-10 12:53:03",
"venue_id": "V0-001-010992661-9",
"tz_city": null,
"stop_time": null,
"venue_name": "SBA Georgia District Office",
"venue_url": "http://atlanta.eventful.com/venues/sba-georgia-district-office-/V0-001-010992661-9?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": null,
"going_count": null,
"all_day": "0",
"latitude": "33.7489",
"groups": null,
"url": "http://atlanta.eventful.com/events/1013-attend-develop-importexport-business-/E0-001-100277583-2?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-100277583-2",
"privacy": "1",
"city_name": "Atlanta",
"link_count": null,
"longitude": "-84.3881",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-10-13 09:30:00",
"tz_id": null,
"description": " Small businesses looking to increase sales and profit, reduce dependence on the domestic market and stabilize seasonal fluctuations should consider importing and exporting.  With nearly 96 percent of consumers living outside the U.S. and two-thirds of the world’s purchasing power in foreign countries, opportunities await U.S. small business.Go where the customers are. There is significant opportunity for small businesses to profit through importing and exporting operations.Do you have what it takes to become a successful international business? Are you ready to make international sales? Importing / Exporting offers great opportunities but requires preparation and planning.This is a two part series taught by international experts from the Georgia Small Business Development Center, a resource partner of the SBA.Module I will aid you in assessing your readiness, understanding what you need to know and consider before pursuing an international strategy. Module II will introduce you to those topics needed to develop and implement your strategy: international pricing and costing issues, proforma export quotations, payment terms, and risk assessment.The workshops will help you gain the knowledge to develop and implement an international  plan. You will become acquainted with the key components of an effective import / export plan.  The instructors will raise questions you should answer to complete your plan and provide the resources to help you answer those questions.    * organizational and product readiness,    * market research,    * guidance for developing your strategy and marketing plan,    * promoting your products in target market, and    * complying with US and foreign regulations. Fee for Module  I is $50 per person and is taught 9:30am - 12:30pmFee for Module II is $50 per person and is taught 1:15pm -  4:30pmBoth modules can be attended as a full day event for a single Fee of $89 per person ",
"modified": "2017-02-10 12:52:14",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "10/13 Attend Develop an Import/Export Business",
"venue_address": "233 Peachtree Street NE , 2nd Floor",
"geocode_type": "City Based GeoCodes",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": {
"small": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/037/789/130-7.jpeg_/1013-attend-develop-importexport-business-30.jpeg",
"height": "48"
},
"width": "48",
"caption": null,
"medium": {
"width": "128",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/037/789/130-7.jpeg_/1013-attend-develop-importexport-business-30.jpeg",
"height": "128"
},
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/037/789/130-7.jpeg_/1013-attend-develop-importexport-business-30.jpeg",
"thumb": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/037/789/130-7.jpeg_/1013-attend-develop-importexport-business-30.jpeg",
"height": "48"
},
"height": "48"
},
"created": "2017-02-10 12:52:14",
"venue_id": "V0-001-010992661-9",
"tz_city": null,
"stop_time": null,
"venue_name": "SBA Georgia District Office",
"venue_url": "http://atlanta.eventful.com/venues/sba-georgia-district-office-/V0-001-010992661-9?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": "30126",
"going_count": null,
"all_day": "0",
"latitude": "33.8133",
"groups": null,
"url": "http://atlanta.eventful.com/events/legal-aid-cobb-county-consultations-/E0-001-098404517-5?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-098404517-5",
"privacy": "1",
"city_name": "Mableton",
"link_count": null,
"longitude": "-84.5519",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-12-03 13:30:00",
"tz_id": null,
"description": " <p><b><i>Legal Aid of Cobb County</i></b> provides civil legal services for many types of cases including:<p>Government Benefits; Consumer Law; Family Law & Domestic Relations; Education; Housing; Health; Employment and other civil (non-criminal) legal services.<p>If you have a civil legal question, then come for a free, brief civil consultation session with a Legal Aid attorney.<p>1:30 – 3:30 pm in Study Room B.<p>Free and open to the public.<p>First come, first serve only – reservations not taken in advance, but can signup at 11am on day of program.<p>Please note: Cobb County Library System and/or its employees do not provide legal advice.</p></p></p></p></p></p></p>",
"modified": "2017-02-01 10:43:46",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "Legal Aid of Cobb County Consultations",
"venue_address": "805 Clay Road",
"geocode_type": "Zip Code Based GeoCodes",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": {
"small": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/035/826/562-6.jpeg_/legal-aid-cobb-county-consultations-62.jpeg",
"height": "48"
},
"width": "48",
"caption": null,
"medium": {
"width": "128",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/035/826/562-6.jpeg_/legal-aid-cobb-county-consultations-62.jpeg",
"height": "128"
},
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/035/826/562-6.jpeg_/legal-aid-cobb-county-consultations-62.jpeg",
"thumb": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/035/826/562-6.jpeg_/legal-aid-cobb-county-consultations-62.jpeg",
"height": "48"
},
"height": "48"
},
"created": "2016-12-07 15:31:13",
"venue_id": "V0-001-005997954-9",
"tz_city": null,
"stop_time": null,
"venue_name": "South Cobb Regional Library",
"venue_url": "http://atlanta.eventful.com/venues/south-cobb-regional-library-/V0-001-005997954-9?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": "30097",
"going_count": null,
"all_day": "0",
"latitude": "33.9914656",
"groups": null,
"url": "http://atlanta.eventful.com/events/catalyst-atlanta-2017-/E0-001-099827134-2?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-099827134-2",
"privacy": "1",
"city_name": "Duluth",
"link_count": null,
"longitude": "-84.0940253",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-10-04 08:30:00",
"tz_id": null,
"description": " Catalyst Atlanta 2017 - Event Details & Cancellation Policy At Catalyst, we believe that the Church is the hope of the world and that those who follow Jesus should be the best leaders in the world. Catalyst Atlanta is an event created to unite, equip and nurture leaders serving the local Church. Whether you&#39;re in full-time ministry or in a volunteer role, this event is intentionally designed so that you can take a few days off from serving to be refreshed and strengthened. Join us for Catalyst Atlanta on October 4-6, 2017!    Cancellation Policy for Catalyst Atlanta 2017:  Catalyst event tickets are non-refundable upon purchase, but fully transferrable to a substitute registrant up to, and including, the day(s) of the event. The transfer of tickets to another attendee can be managed in your Eventbrite account by contacting a Catalyst Concierge at 888.334.6569, or at registration at the event. Upon purchase, Catalyst registrants will begin receiving exclusive content, offers and product information from Catalyst via our e-newsletters. You may unsubscribe from these newsletters at any time by following the link provided at the bottom of each email. We will not share your email address with anyone.  ",
"modified": "2017-01-25 12:28:55",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "Catalyst Atlanta 2017",
"venue_address": "6400 Sugarloaf Parkway",
"geocode_type": "EVDB Geocoder",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": {
"small": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/037/511/513-3.png_/catalyst-atlanta-2017-13.png",
"height": "48"
},
"width": "48",
"caption": null,
"medium": {
"width": "128",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/medium/I0-001/037/511/513-3.png_/catalyst-atlanta-2017-13.png",
"height": "128"
},
"url": "http://d1marr3m5x4iac.cloudfront.net/images/small/I0-001/037/511/513-3.png_/catalyst-atlanta-2017-13.png",
"thumb": {
"width": "48",
"url": "http://d1marr3m5x4iac.cloudfront.net/images/thumb/I0-001/037/511/513-3.png_/catalyst-atlanta-2017-13.png",
"height": "48"
},
"height": "48"
},
"created": "2017-01-25 12:28:55",
"venue_id": "V0-001-000183247-8",
"tz_city": null,
"stop_time": null,
"venue_name": "Infinite Energy Center - Infinite Energy Arena",
"venue_url": "http://atlanta.eventful.com/venues/infinite-energy-center-infinite-energy-arena-/V0-001-000183247-8?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": "30030",
"going_count": null,
"all_day": "0",
"latitude": "33.7739660",
"groups": null,
"url": "http://atlanta.eventful.com/events/caroline-herring-/E0-001-099643872-1?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-099643872-1",
"privacy": "1",
"city_name": "Decatur",
"link_count": null,
"longitude": "-84.2964490",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-10-27 19:00:00",
"tz_id": null,
"description": " <br> With accolades and endorsements from critics and fellow musicians alike, Signature Sounds recording artist Caroline Herring has emerged as one of the most literate and distinctive songwriters of her generation and one of the freshest voices to hit the music scene in a long time. Since her debut in 2001, Herring has gained a devoted following and much critical acclaim. Named &quot;Best New Artist&quot; at the Austin Music Awards, Caroline has been profiled on NPR&#39;s &quot;All Things Considered,&quot; been a guest on Garrison Keillor&#39;s &quot;A Prairie Home Companion,&quot; and was the only American representative involved in the prestigious Cecil Sharp Project in England, a group of musicians commissioned to compose music based on the life and collections of the famous song catcher.Caroline has established herself as a lyrical and inventive songwriter and a singer whose vocals never fail to move the listener with her high trills and rich vibrato. The Mississippi native, now based in Atlanta, has been compared to Lucinda Williams, Joan Baez, and even Mozart.Caroline&#39;s songs are always perfect little mysteries and powerful, hopeful love stories, but they are never simple thrilling romances. They are complex, modern, tradition-influenced compositions about love and hate and everything in between. On CAMILLA, her recently released sixth CD, she has created her most profound album yet with a collection of ten deeply moving songs.",
"modified": "2017-01-19 11:05:09",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "Caroline Herring",
"venue_address": "515-B N. McDonough Street",
"geocode_type": "EVDB Geocoder",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": null,
"created": "2017-01-19 11:05:09",
"venue_id": "V0-001-000445186-7",
"tz_city": null,
"stop_time": null,
"venue_name": "Eddie's Attic",
"venue_url": "http://atlanta.eventful.com/venues/eddies-attic-/V0-001-000445186-7?utm_source=apis&utm_medium=apim&utm_campaign=apic"
},
{
"watching_count": null,
"olson_path": "America/New_York",
"calendar_count": null,
"comment_count": null,
"region_abbr": "GA",
"postal_code": "30126",
"going_count": null,
"all_day": "2",
"latitude": "33.8468611",
"groups": null,
"url": "http://atlanta.eventful.com/events/silver-comet-half-full-marathon-2017-/E0-001-099261382-9?utm_source=apis&utm_medium=apim&utm_campaign=apic",
"id": "E0-001-099261382-9",
"privacy": "1",
"city_name": "Mableton",
"link_count": null,
"longitude": "-84.5856039",
"country_name": "United States",
"country_abbr": "USA",
"region_name": "Georgia",
"start_time": "2017-10-28 00:00:00",
"tz_id": null,
"description": null,
"modified": "2017-01-07 23:00:38",
"venue_display": "1",
"tz_country": null,
"performers": null,
"title": "Silver Comet Half & Full Marathon 2017",
"venue_address": "4342 Floyd Rd",
"geocode_type": "EVDB Geocoder",
"tz_olson_path": null,
"recur_string": null,
"calendars": null,
"owner": "evdb",
"going": null,
"country_abbr2": "US",
"image": null,
"created": "2017-01-07 23:00:38",
"venue_id": "V0-001-002387857-9",
"tz_city": null,
"stop_time": "2017-10-29 00:00:00",
"venue_name": "Silver Comet Trail",
"venue_url": "http://atlanta.eventful.com/venues/silver-comet-trail-/V0-001-002387857-9?utm_source=apis&utm_medium=apim&utm_campaign=apic"
}
]
}
}
export{data};